# Build a Universal Windows Platform project using Visual Studio.
# Add steps that test and distribute an app, save build artifacts, and more:
# https://aka.ms/yaml

# trigger: none
# # - master

# pool:
#   vmImage: 'windows-latest'

# variables:
#   solution: '**/*.sln'
#   buildPlatform: 'x86|x64|ARM'
#   buildConfiguration: 'Release'
#   appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'
#   projectToBuild: '**/*.csproj'


# steps:
# - task: NuGetToolInstaller@1

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution)'

# - task: DownloadSecureFile@1
#   inputs:
#     secureFile: 'UWP_StoreKey.pfx'
#     retryCount: '2'

# - task: CopyFiles@2
#   inputs:
#     SourceFolder: '$(Agent.TempDirectory)'
#     Contents: 'UWP_StoreKey.pfx'
#     TargetFolder: 'CryptoTracker\'

# - task: VSBuild@1
#   inputs:
#     platform: 'x64'
#     solution: '$(solution)'
#     configuration: '$(buildConfiguration)'
#     msbuildArgs: '/p:AppxBundlePlatforms="$(buildPlatform)" /p:AppxPackageDir="$(appxPackageDir)" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload'

# # This takes the package created by Azure Pipelines and
# # places it in a location where you can download it later. 
# - task: PublishBuildArtifacts@1
#   displayName: 'Publish Artifact: drop'
#   inputs:
#     PathtoPublish: '$(build.artifactstagingdirectory)'

# # Try to remove the *_Test folder created
# - task: DeleteFiles@1
#   inputs:
#     SourceFolder: '$(build.artifactStagingDirectory)\AppxPackages\*_Test'
#     Contents: '**'
#     RemoveSourceFolder: true